### Signup - Send OTP

POST http://localhost:8000/api/v1/signup
Content-Type: application/json

{
    "username": "nikhilcughan",
    "email": "nikhilsinghdfg@gmail.com",
    "password": "dhn245dfgAA@"
}

###


### Verify OTP

POST http://localhost:6000/api/v1/verify-otp
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com",
    "otp": "751441"

}



### login test 

POST http://localhost:8000/api/v1/Login
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com",
    "password": "dhn245dfgAA@"
}

###

### Get Profile 

GET http://localhost:6000/api/v1/profile 
Cookie: accessToken=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY1YmUyOGJmZDg2OTdkMGZlZjgwYiIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDA0NDU0MSwiZXhwIjoxNzg0MDQ1NDQxfQ.JQqX9HXqIkJPLQPxKb81BNrRQxvtewE4PtcYIOh-URg


###

### Refresh Access Token

POST http://localhost:6000/api/v1/refresh-token
Cookie: refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY1YmUyOGJmZDg2OTdkMGZlZjgwYiIsImlhdCI6MTc4NDA0NDU0MSwiZXhwIjoxNzg1MzQwNTQxfQ.cwR82udEWtWgyP0x5HqkkohtyYWKSocQREyFo-Kq694

### 
### Logout 
POST http://localhost:6000/api/v1/logout 
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY1ZmM5ZWI3ZjA1MDQxMzhkYjI5MSIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0MDQ1Nzc3LCJleHAiOjE3ODQwNDY2Nzd9.XBdYAQT7leSBMz9F8y3KnFdzvKP34TLcnhx_BP3-jFo



### Update Profile

PATCH http://localhost:6000/api/v1/Update-Profile
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY1YmUyOGJmZDg2OTdkMGZlZjgwYiIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDA0NDU0MSwiZXhwIjoxNzg0MDQ1NDQxfQ.JQqX9HXqIkJPLQPxKb81BNrRQxvtewE4PtcYIOh-URg

{
    "username": "vimal"
}


### Change Password

PATCH http://localhost:6000/api/v1/change-password
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY1YmUyOGJmZDg2OTdkMGZlZjgwYiIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDA0NDU0MSwiZXhwIjoxNzg0MDQ1NDQxfQ.JQqX9HXqIkJPLQPxKb81BNrRQxvtewE4PtcYIOh-URg

{
    "oldPassword": "dhn245dfgAA@",
    "newPassword": "pa22ss123@asA"
}


### Deactivate Account

PATCH http://localhost:6000/api/v1/deactivate-account
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY1Y2NkOGJmZDg2OTdkMGZlZjgwZCIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDA0NDc2NiwiZXhwIjoxNzg0MDQ1NjY2fQ.WB9qm2wwmwgc23JpzguQL7Xip-CPf3l39QWT1o8wVpg

### Delete Account

DELETE http://localhost:6000/api/v1/delete-account
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNTY1ZDQ1OGJmZDg2OTdkMGZlZjgwZiIsImVtYWlsIjoibmlraGlsc2luZ2gyNzY0QGdtYWlsLmNvbSIsImlhdCI6MTc4NDA0NDg4MSwiZXhwIjoxNzg0MDQ1NzgxfQ.QtFM4byFGSYwcGHYSocaak5c6uYC2oToCO1Lf6JMaJA

{
    "password": "dhn245dfgAA@"
}



### Forgot Password

POST http://localhost:6000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "nikhilsingh2764@gmail.com"
}


### Reset Password

POST http://localhost:6000/api/v1/reset-password
Content-Type: application/json

{
    "email": "nikhilsingh2764@gmail.com",
    "otp": "406966",
    "newPassword": "dhn245dfgA@"
}


##############################################################################################################################################################################################################################################################

### create new business


POST http://localhost:6000/api/v1/business
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


{
  "businessName": "Nextpen Solutions",
  "ownerName": "Rahul Sharma",
  "email": "skyline.tech@example.com",
  "phone": "9123456783",
  "gstNumber": "27ABCDE1234F1Z5",
  "address": {
    "addressLine1": "45 Park Street",
    "addressLine2": "",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "400001"
  },
  "currency": "INR",
  "signature": "https://example.com/rahul-signature.png",
  "logo": "https://example.com/skyline-logo.png",
  "invoicePrefix": "SKY",
  "invoiceStartNumber": 1001,
  "termsAndConditions": "Payment is due within 15 days."
}

### get business profile

GET http://localhost:6000/api/v1/business
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NDUzOTQwLCJleHAiOjE3ODQ0NTQ4NDB9.7GZW4uIlIwncCjIV-xz-Fbi5KMQ1yvEw0NZnvIjZcA4



### delete business profile

DELETE  http://localhost:6000/api/v1/business
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NDUzOTQwLCJleHAiOjE3ODQ0NTQ4NDB9.7GZW4uIlIwncCjIV-xz-Fbi5KMQ1yvEw0NZnvIjZcA4


### Update Business

PATCH http://localhost:6000/api/v1/business
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NDUzOTQwLCJleHAiOjE3ODQ0NTQ4NDB9.7GZW4uIlIwncCjIV-xz-Fbi5KMQ1yvEw0NZnvIjZcA4


{
  "businessName": "Nextpen Solutions",
  "phone": "9123456783",
  "city": "pune"
}




##############################################################################################################################################################################################################################################################

### create new product


POST http://localhost:6000/api/v1/product
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ

{
    "productName": "Laptop",
    "description": "HP 15S Laptop",
    "category": "Electronics",
    "unit": "piece",
    "price": 5000,
    "taxRate": 12,
    "discount": 5
}



### Get All Products

GET http://localhost:6000/api/v1/product
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


### Get Product By ID

GET http://localhost:6000/api/v1/product/6a5dc7815f4df1ac8be0b6d1
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


### Update Product

PATCH http://localhost:6000/api/v1/product/6a5dc7815f4df1ac8be0b6d1
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


{
    "productName": "Dell Inspiron 15",
    "description": "Dell Inspiron 15 12th Gen Intel i5 Laptop",
    "category": "Electronics",
    "unit": "piece",
    "price": 58999,
    "taxRate": 18,
    "discount": 10
}

### Delete Product

DELETE http://localhost:6000/api/v1/product/6a5dc7815f4df1ac8be0b6d1
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ



##############################################################################################################################################################################################################################################################


### Create Customer

POST http://localhost:8000/api/v1/customer
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NjIxMzI0LCJleHAiOjE3ODQ2MjIyMjR9.89dvqCwrDLg9UyXYyYw7Vv-P_b0bZ-N-8OC8z1q3NcA


{
    "customerName": "Priya Verma",
    "email": "nikhilsinghdfg@gmail.com",
    "phone": "8407937952",
    "companyName": "TechNova Solutions",
    "gstNumber": "27ABCDE1234F1Z5",
    "customerType": "Business",
    "notes": "Preferred customer",

    "billingAddress": {
        "addressLine1": "101 Park Street",
        "addressLine2": "Near City Mall",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411001"
    },

    "shippingAddress": {
        "addressLine1": "Warehouse 5",
        "addressLine2": "MIDC Phase 2",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411045"
    }
}

### Get All Customers

GET http://localhost:6000/api/v1/customer
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMxODA3LCJleHAiOjE3ODQ1MzI3MDd9.6hjTYKEKn6Himwia9DiCDApUVvIG1g6LlsM10Dp3Dk4


### Get Customer By ID

GET http://localhost:6000/api/v1/customer/6a5dcb76d1ee2c7e359307cd
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMxODA3LCJleHAiOjE3ODQ1MzI3MDd9.6hjTYKEKn6Himwia9DiCDApUVvIG1g6LlsM10Dp3Dk4


### Update Customer

PATCH http://localhost:6000/api/v1/customer/6a5dcb76d1ee2c7e359307cd
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMxODA3LCJleHAiOjE3ODQ1MzI3MDd9.6hjTYKEKn6Himwia9DiCDApUVvIG1g6LlsM10Dp3Dk4

{
    "customerName": "Priya Verma Updated",
    "phone": "9988776655",
    "companyName": "TechNova Pvt Ltd",
    "notes": "VIP customer",

    "billingAddress": {
        "addressLine1": "202 FC Road",
        "addressLine2": "Near Metro Station",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411004"
    }
}





### Delete Customer

DELETE http://localhost:6000/api/v1/customer/6a5dcb76d1ee2c7e359307cd
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMxODA3LCJleHAiOjE3ODQ1MzI3MDd9.6hjTYKEKn6Himwia9DiCDApUVvIG1g6LlsM10Dp3Dk4




##############################################################################################################################################################################################################################################################


### Create Invoice

POST http://localhost:8000/api/v1/invoice
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NjMzODE1LCJleHAiOjE3ODQ2MzQ3MTV9.OQb2tXjYQ8Colp9X9pzJy_5o-G4FIb4ZPKLnFdkTOcI


{
  "customerId": "6a5f2a382aa82faf175f73a8",
  "items": [
    {
      "productId": "6a5dc858c1ba391834611985",
      "quantity": 2
    }
  ],
"dueDate": "2026-07-01",
  "status": "Paid",
  "notes": "Invoice 4"
}

### ============================================
### Get All Invoices
### ============================================

GET http://localhost:6000/api/v1/invoice
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Pagination - Page 1
### ============================================

GET http://localhost:6000/api/v1/invoice?page=1&limit=5
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Pagination - Page 2
### ============================================

GET http://localhost:6000/api/v1/invoice?page=2&limit=5
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc




### ============================================
### Search by Customer Name
### ============================================

GET http://localhost:6000/api/v1/invoice?search=Rahul Sharma
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc



### ============================================
### Search by Email
### ============================================

GET http://localhost:6000/api/v1/invoice?search=rahul@gmail.com
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc



### ============================================
### Search by Invoice Number
### ============================================

GET http://localhost:6000/api/v1/invoice?search=INV-1001
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc



### ============================================
### Filter - Pending
### ============================================

GET http://localhost:6000/api/v1/invoice?status=Pending
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc



### ============================================
### Filter - Paid
### ============================================

GET http://localhost:6000/api/v1/invoice?status=Paid
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Filter - Overdue
### ============================================

GET http://localhost:6000/api/v1/invoice?status=Overdue
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Date Filter
### ============================================

GET http://localhost:6000/api/v1/invoice?startDate=2026-07-01&endDate=2026-07-31
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Sort by Created Date (Newest)
### ============================================

GET http://localhost:6000/api/v1/invoice?sortBy=createdAt&sortOrder=desc
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Sort by Created Date (Oldest)
### ============================================

GET http://localhost:6000/api/v1/invoice?sortBy=createdAt&sortOrder=asc
Cookie: accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc

### ============================================
### Sort by Grand Total
### ============================================

GET http://localhost:6000/api/v1/invoice?sortBy=grandTotal&sortOrder=desc
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc

### ============================================
### Combined Filter + Search + Pagination
### ============================================

GET http://localhost:6000/api/v1/invoice?status=Pending&search=Rahul&page=1&limit=5&sortBy=createdAt&sortOrder=desc
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc

### ============================================
### Invalid Status
### ============================================

GET http://localhost:6000/api/v1/invoice?status=Invalid
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Invalid Page
### ============================================

GET http://localhost:6000/api/v1/invoice?page=-1&limit=5
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Invalid Limit
### ============================================

GET http://localhost:6000/api/v1/invoice?limit=abc
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTc5ODUxLCJleHAiOjE3ODQ1ODA3NTF9.MuB-WgepHnCtD_SthHsJHbEdjZXE3WzVLWkGYNA3Xwc


### ============================================
### Unauthorized
### ============================================

GET http://localhost:6000/api/v1/invoice



### Get Invoice By ID

GET http://localhost:6000/api/v1/invoice/6a5e8757c128c6fb4cc25715
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NjEyNzc5LCJleHAiOjE3ODQ2MTM2Nzl9.wI4nifmI49Zkv_EbzGt7D963t0x5scWezz_ZpgwAvmA

### Update Invoice


PATCH http://localhost:6000/api/v1/invoice/6a5e8757c128c6fb4cc25715
Content-Type: application/json
Cookie: accessToken=  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NjE0MDM0LCJleHAiOjE3ODQ2MTQ5MzR9.GXmGFM7KqpJIq1KLOSN5UtZWfd3WhZn2d9TMQ1wOPcM

{
  "customerId": "6a5dca902faa65acbee1e4d7",
  "items": [
    {
      "productId": "6a5dc858c1ba391834611985",
      "quantity": 3
    }
  ],
  "dueDate": "2026-08-10",
  "status": "Pending",
  "notes": "Updated invoice after customer request"
}




### Update Invoice


DELETE  http://localhost:8000/api/v1/invoice/6a5e893ac128c6fb4cc2571a
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NjE2MTYxLCJleHAiOjE3ODQ2MTcwNjF9.FEagP6Cq-PcUKr6StKwEVK81IZgT9SBNfX24iMoYA2A




### Send Invoice Email
POST http://localhost:8000/api/v1/invoice/6a5f55b13ddc6817cb6a0855/email
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NjMyNTY2LCJleHAiOjE3ODQ2MzM0NjZ9.AAuWvHJAYMJUjakwq4C735ImwS0upMLBCk5cS3dYVGs

### Duplicate Invoice
POST http://localhost:8000/api/v1/invoice/6a5f55b13ddc6817cb6a0855/duplicate
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NjMyNTY2LCJleHAiOjE3ODQ2MzM0NjZ9.AAuWvHJAYMJUjakwq4C735ImwS0upMLBCk5cS3dYVGs