### Signup - Send OTP

POST http://localhost:8000/api/v1/signup
Content-Type: application/json

{
    "username": "nikhilcs",
    "email": "nikhilsinghd276@gmail.com",
    "password": "dhn245dfgAA@"
}

###


### Verify OTP

POST http://localhost:8000/api/v1/verify-otp
Content-Type: application/json

{
    "email": "nikhilsinghd276@gmail.com",
    "otp": "626127"

}



### login test 

POST http://localhost:8000/api/v1/Login
Content-Type: application/json

{
    "email": "nikhilsinghd276@gmail.com",
    "password": "dhn245dfgAA@"
}

###

### Get Profile 

GET http://localhost:8000/api/v1/profile 
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2Nzg4MiwiZXhwIjoxNzg1MjcwODgyfQ.SoQMsOWcSbztYzg-FOpLkRvaKIb3Vigp_xyhc6XQb-U


###

### Refresh Access Token

POST http://localhost:8000/api/v1/refresh-token
Cookie: refreshToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImlhdCI6MTc4NTI2Nzc5MCwiZXhwIjoxNzg2NTYzNzkwfQ.Vqhx80OOXc7yBV4FZrqGcRENKR8BN0s3FGReDSMfJfc

 


### Logout 
POST http://localhost:8000/api/v1/logout 
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNTJiZDk3YWIzNzJjZDllMDRhYSIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg1MjY3NTIzLCJleHAiOjE3ODUyNzA1MjN9.VQHQn4ZJ2NT4FSxrUHRs4pjJkVWBQPPZV51FMat4uP4



### Update Profile

PATCH http://localhost:8000/api/v1/Update-Profile
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNDBjODYzYzQzNmQyNDdlOThiNSIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg1MjY3MjE5LCJleHAiOjE3ODUyNzAyMTl9.x27l1O_KeenS76vmGKh3hfFAkxfVzdgPHN0bjQJiNXo

{
    "username": "vimal"
}


### Change Password

PATCH http://localhost:8000/api/v1/change-password
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNDBjODYzYzQzNmQyNDdlOThiNSIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg1MjY3MjE5LCJleHAiOjE3ODUyNzAyMTl9.x27l1O_KeenS76vmGKh3hfFAkxfVzdgPHN0bjQJiNXo

{
    "oldPassword": "dhn245dfgAA@",
    "newPassword": "qazQAZ123@AS#AS"
}


### Deactivate Account

PATCH http://localhost:8000/api/v1/deactivate-account
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNTJiZDk3YWIzNzJjZDllMDRhYSIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg1MjY3NTQ5LCJleHAiOjE3ODUyNzA1NDl9.b7F37CGaxHn821ml_tH2EKzSlM1gdblYaHCtoznasYg



### Delete Account

DELETE http://localhost:8000/api/v1/delete-account
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNWZmYmZiMjM5Njg3M2VhNjc1MyIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2NzczMCwiZXhwIjoxNzg1MjcwNzMwfQ.mO_CnSd7G5_iIPnJaoF70LQj73qIcnQWCoNnsATRkGo

{
    "password": "dhn245dfgAA@"
}



### Forgot Password

POST http://localhost:8000/api/v1/forgot-password
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com"
}


### Reset Password

POST http://localhost:8000/api/v1/reset-password
Content-Type: application/json

{
    "email": "nikhilsinghdfg@gmail.com",
    "otp": "531006",
    "newPassword": "dhn245dfgA@123",
    "confirmPassword": "dhn245dfgA@123"
}



##############################################################################################################################################################################################################################################################


### create new business


POST http://localhost:8000/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2Nzk1MiwiZXhwIjoxNzg1MjcwOTUyfQ.JnyUuCjFWwVioKbLLcGanJ7y72cP2xishW2uHFYI1AU


{
  "businessName": "Nextpen Solutions pvt lmt",
  "ownerName": "Rahul gadlhi",
  "email": "skyline.tech@example.com",
  "phone": "9123456783",
  "gstNumber": "27ABCDE1234F1Z5",
  "address": {
    "addressLine1": "45 Park Street",
    "addressLine2": "",
    "city": "Pune",
    "state": "Maharashtra",
    "country": "India",
    "postalCode": "400001"
  },
  "currency": "INR",
  "signature": "https://example.com/rahul-signature.png",
  "logo": "https://example.com/skyline-logo.png",
  "invoicePrefix": "SKY",
  "invoiceStartNumber": 1001,
  "termsAndConditions": "Payment is due within 15 days."
}


### get business profile

GET http://localhost:8000/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2Nzk1MiwiZXhwIjoxNzg1MjcwOTUyfQ.JnyUuCjFWwVioKbLLcGanJ7y72cP2xishW2uHFYI1AU



### delete business profile

DELETE  http://localhost:8000/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2Nzk1MiwiZXhwIjoxNzg1MjcwOTUyfQ.JnyUuCjFWwVioKbLLcGanJ7y72cP2xishW2uHFYI1AU


### Update Business

PATCH http://localhost:8000/api/v1/business
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2Nzk1MiwiZXhwIjoxNzg1MjcwOTUyfQ.JnyUuCjFWwVioKbLLcGanJ7y72cP2xishW2uHFYI1AU

{
  "businessName": "Nextpen pvt lmt",
  "phone": "9123456783",
  "city": "pune"
}




##############################################################################################################################################################################################################################################################

### create new product


POST http://localhost:8000/api/v1/product
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2Nzk1MiwiZXhwIjoxNzg1MjcwOTUyfQ.JnyUuCjFWwVioKbLLcGanJ7y72cP2xishW2uHFYI1AU

{
    "productName": "Laptop",
    "description": "HP 15S Laptop",
    "category": "Electronics",
    "unit": "piece",
    "price": 5000,
    "taxRate": 12,
    "discount": 5
}



### Get All Products

GET http://localhost:8000/api/v1/product
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2Nzk1MiwiZXhwIjoxNzg1MjcwOTUyfQ.JnyUuCjFWwVioKbLLcGanJ7y72cP2xishW2uHFYI1AU


### Get Product By ID

GET http://localhost:8000/api/v1/product/6a69076264a41a108c46d72c
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


### Update Product

PATCH http://localhost:8000/api/v1/product/6a69076264a41a108c46d72c
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


{
    "productName": "Dell Inspiron 15",
    "description": "Dell Inspiron 15 12th Gen Intel i5 Laptop",
    "category": "Electronics",
    "unit": "piece",
    "price": 58999,
    "taxRate": 18,
    "discount": 10
}

### Delete Product

DELETE http://localhost:8000/api/v1/product/6a69076264a41a108c46d72c
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ



##############################################################################################################################################################################################################################################################


### Create Customer

POST http://localhost:8000/api/v1/customer
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


{
    "customerName": "liya naveed",
    "email": "nikhilsinghdfg@gmail.com",
    "phone": "8407937952",
    "companyName": "TechNova Solutions",
    "gstNumber": "27ABCDE1234F1Z5",
    "customerType": "Business",
    "notes": "Preferred customer",

    "billingAddress": {
        "addressLine1": "101 Park Street",
        "addressLine2": "Near City Mall",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411001"
    },

    "shippingAddress": {
        "addressLine1": "Warehouse 5",
        "addressLine2": "MIDC Phase 2",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411045"
    }
}

### Get All Customers

GET http://localhost:8000/api/v1/customer
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


### Get Customer By ID

GET http://localhost:8000/api/v1/customer/6a6907f164a41a108c46d72f
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


### Update Customer

PATCH http://localhost:8000/api/v1/customer/6a6907f164a41a108c46d72f
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ

{
    "customerName": "Priya Verma Updated",
    "phone": "9988776655",
    "companyName": "TechNova Pvt Ltd",
    "notes": "VIP customer",

    "billingAddress": {
        "addressLine1": "202 FC Road",
        "addressLine2": "Near Metro Station",
        "city": "Pune",
        "state": "Maharashtra",
        "country": "India",
        "postalCode": "411004"
    }
}





### Delete Customer

DELETE http://localhost:8000/api/v1/customer/6a6907f164a41a108c46d72f
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ




##############################################################################################################################################################################################################################################################


### Create Invoice

POST http://localhost:8000/api/v1/invoice
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


{
  "customerId": "6a69080a64a41a108c46d730",
  "items": [
    {
      "productId": "6a6907cd64a41a108c46d72d",
      "quantity": 2
    }
  ],
"dueDate": "2026-02-01",
  "status": "Pending",
  "notes": "Invoice 8"
}


### Get Invoice By ID

GET http://localhost:8000/api/v1/invoice/6a69093564a41a108c46d733
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ





### Update Invoice


PATCH http://localhost:8000/api/v1/invoice/6a69093564a41a108c46d733
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ

{
  "customerId": "6a69080a64a41a108c46d730",
  "items": [
    {
      "productId": "6a6907cd64a41a108c46d72d",
      "quantity": 3
    }
  ],
  "dueDate": "2026-08-10",
  "status": "Pending",
  "notes": "Updated invoice after customer request"
}




### delete Invoice


DELETE  http://localhost:8000/api/v1/invoice/6a69093564a41a108c46d733
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ




### Send Invoice Email
POST http://localhost:8000/api/v1/invoice/6a6909c864a41a108c46d734/email
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2ODczOSwiZXhwIjoxNzg1MjcxNzM5fQ.VY6cTTTZz-YaY8NeHFekYZ_MV2Kzzf2cDxD-2xpLlM0

### Download Invoice PDF

GET http://localhost:8000/api/v1/invoice/6a6909c864a41a108c46d734/pdf
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNjkwNjQ2YmZiMjM5Njg3M2VhNjc1NiIsImVtYWlsIjoibmlraGlsc2luZ2hkMjc2QGdtYWlsLmNvbSIsImlhdCI6MTc4NTI2ODczOSwiZXhwIjoxNzg1MjcxNzM5fQ.VY6cTTTZz-YaY8NeHFekYZ_MV2Kzzf2cDxD-2xpLlM0


### Duplicate Invoice
POST http://localhost:8000/api/v1/invoice/6a6909c864a41a108c46d734/duplicate
Content-Type: application/json
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

################################################################################################

### Dashboard Stats

GET http://localhost:8000/api/v1/
Cookie: accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ

### Dashboard Search Test

GET http://localhost:8000/api/v1/?search=rahul
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


### Dashboard Filter By Status - Paid

GET http://localhost:8000/api/v1/?status=Paid
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQxk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ



### Dashboard Filter By Status - Pending

GET http://localhost:8000/api/v1/?status=Pending
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ


### Dashboard Sort Latest Invoice First

GET http://localhost:8000/api/v1/?sort=-createdAt
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQXk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ



### Dashboard Sort Oldest Invoice First

GET http://localhost:8000/api/v1/?sort=createdAt
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQxk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ

### Dashboard Pagination Page 1 Limit 5

GET http://localhost:8000/api/v1/?page=1&limit=5
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQxk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ




### Dashboard Combined Test
### Search + Filter + Sort + Pagination

GET http://localhost:8000/api/v1/?search=tech&status=Paid&sort=-createdAt&page=1&limit=10
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNWM4NmY2ODRkMDZjMmQ0MThkY2U1YiIsImVtYWlsIjoibmlraGlsc2luZ2hkZmdAZ21haWwuY29tIiwiaWF0IjoxNzg0NTMwNzMxLCJleHAiOjE3ODQ1MzE2MzF9.vMCQxk6_TeFVTMtnXS7fEJiVEftbiXHlwMys49y3uyQ

